src/api/supabase.ts, src/app/room/[id]/page.tsx, src/components/room/meeting/user/UserList.tsx, src/hooks/useDataQuery.ts, src/types/supabase.ts, src/utils/supabase/server.ts
closed #17
[할일] Feature : 유저리스트 사이드바 #17
```
데이터 테이블에 목업데이터를 구성, 올바른 rooms와 login user의 데이터를 가져오는 지 확인
```
```
기존, useRouter와 useParams를 사용했는데, SSR로 페이지를 운영하기 위해서 params로 변경
getUsers와 getSession중, 필요한 용도가 더 부합하는 getSession을 선택했음.
```
=> [feat] params를 통해 rooms테이블의 데이터를 받아올 수 있는 기능

src/components/room/meeting/place/KakaoMap.tsx, src/components/room/meeting/place/RangeController.module.css, src/components/room/meeting/place/RangeController.tsx
closed #29 
스크린샷 및 레퍼런스 참고
- css 로 닷슬라이더 구현 복붙 -> 불필요한 css 있을 수 있음. 
- 지도 마커 랑 같은 부모 태그사용으로 강제로 맵안에서 표시됨. 
- [라디오 버튼으로 닷 슬라이더 구현](https://codepen.io/brandonmcconnell/pen/Zqjdmg)
=> [feat/map radius] 지도 검색 원 반경 컨트롤러 기능 구현

src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx
closed #16 
```
1. 드래그로 범위 설정 구현 시도했으나, 데이터만 담기고 UI 구현이 안 됨
2. 시작 날짜 , 마지막 날짜로 범위 선택 후 범위 안에 속한 날짜를 데이터로 담으려 했으나 안 됨
3. 유저가 선택한 첫 날짜, 마지막 날짜만 있는 상로 되돌림
```
```
```
```
```
=> [feat/room schedule] 캘린더 첫 날짜, 마지막 날짜로 범위 선택 가능

.eslintrc.json, src/components/room/meeting/place/search/SearchBar.tsx
build시 eslint에 걸려 compile 에러 발생
```
eslint 설정 파일에서 "react-hooks/exhaustive-deps"  rule 추가 후 설정 "off"
```
```
```
<p>적용 전</p>
<p>적용 후</p>
=> [fix/room-place_search] eslint "react-hooks/exhaustive-deps" rule 추가 및 적용

src/api/supabase.ts, src/app/page.tsx, src/app/room/[id]/page.tsx, src/components/layout/Header.tsx, src/components/room/meeting/Meeting.tsx, src/components/room/meeting/calender/Calender.tsx, src/middlewares/protectRoute.ts, src/utils/supabase/server.ts
#28 
```
1. 날짜 범위로 선택 시도한 모든 코드들을 삭제 (추가 구현 기능으로 완전 빼놨음)
2. 단일 선택 날짜들 모두 start date, end date로 supabase에 업로드
```
```
```
```
```
1. 다른 date Picker, day Picker와 같은 캘린더
=> [Feature/upload schedule] 날짜 단일 선택만 가능, 선택한 날짜 모두 supabase에 담김

next.config.mjs, src/app/page.tsx, src/components/my-owl/profile/editable/modal/Modal.tsx, src/components/room/meeting/calender/Calender.tsx
closed #49 
```
1. isValidImageUrl : 유저가 삽입한 url이 유효한 이미지 url인지 확인하는 로직 (불완전)
2. handleChangeURL : 유저가 입력하는 url을 받아 state 변경
3. handleUploadURL : 유저가 삽입한 url을 유저의 profile_url로 변경
```
URL 확인 로직에 다음과 같이 http header를 확인해서 로직을 강화하려고 하였으나, fetch 관련하여 에러가 발생하여 빼놓은 상태입니다. 무엇이 문제인지 잘 모르겠는데, 원인을 아신다면 코멘트 절실하게 부탁드립니다😂
```typescript
try {
// HTTP 요청을 보내서 응답의 Content-Type 확인
const response = await fetch(url);
const contentType = response.headers.get('content-type');
// Content-Type이 이미지인지 확인
if (contentType && contentType.startsWith('image/')) {
return true;
}
} catch (error) {
console.error('Error while validating image URL:', error);
}
return false;
```
url 확인 로직을 추가했음에도 불구하고, .jpgdosd 나 . 만 넣었을 때 업로드가 되는 문제가 있습니다.
TroubleShotting이 해결되면 함께 해결되는 문제로 보이는데, 해결 방안을 잘 모르겠어요.
=> [feat/profile] 프로필 사진 url 업로드 변경 기능 구현

src/api/supabaseSSR/supabase.ts, src/app/room/[id]/page.tsx, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/place/LocationPicker.tsx, src/components/room/sidebar/Sidebar.tsx, src/components/room/sidebar/user/UserList.tsx, src/utils/supabase/userDataFetch.ts
#53 
```
1. 데이터 동기화 후 정렬하는 로직을 구현했습니다.
3. realtime db를 적용하는 위치를 변경했습니다.
```
```
1. 현재 유저의 start_location 데이터를 업데이트 로직에서 업데이트 후 바로 적용이 되어서 정렬 로직을 거치지 않고 있습니다.
2. 해당하는 부분의 값 중, start_location을 의존성 배열에 적용시킬 예정입니다.
```
=> [feature/database] : realtime db의 위치를 변경했습니다.

src/app/page.tsx, src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx
#28 
```
내가 선택한 일정과 다른 유저가 선택한 일정들을 모두 달력에 표시해줍니다.
중복 선택을 제외하고 다른 날짜를 선택할 수 있습니다.
```
```
```
```
```
=> [feat/show schedule]  유저가 선택한 모든 일정을 달력에 표시

src/components/room/meeting/Meeting.tsx, src/components/room/meeting/calender/Calender.tsx
closed #28 
```
1. 다른 유저가 선택한 일정 클릭 시, 중복으로 선택 가능합니다.
2. 중복으로 선택한 일정은 겹치는 횟수 누적으로 채도 확인 가능합니다.
3. 건너뛰기와 다음 버튼 클릭 시 장소 탭으로 전환됩니다.
```
userSchedules를 selectedDate와 동일한 선에서 비교하였으나, 따로 분리했습니다.
git reset과 rebase에 대해 확실히 알게 되었습니다.
=> [feat/show schedule] 다른 유저가 선택한 일정 위에 중복 선택 가능

src/api/supabaseCSR/supabase.ts, src/app/room/[id]/page.module.css, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/Sidebar.tsx
#53 
```
1. realtime 데이터로 업데이트 된 db를 재정렬하는 기능을 추가하였습니다.
2. 캘린더에 필요한 realtime 코드를 작성하였습니다.
3. 필요한 데이터를 분리하여 작성하였습니다 ( 월요일 클린코드데이 때 작업)
```
```
1. useEffect에 의존성 배열로 존재하기 때문에 현재 기능만 구현된 상태입니다.
2. 더 나은 위치에서 realtime base를 적용해야합니다.
3. 캘린더에서 적용시키는 realtime db는 캘린더 영역만을 사용합니다.
```
=> [Feature/database]  realtime db를 지도에 적용, 

src/api/supabaseCSR/supabase.ts, src/components/room/meeting/place/LocationPicker.tsx, src/store/store.ts, src/types/place.types.ts, src/types/supabase.ts, src/utils/objectValidate.ts
closed #69 
```
경도 위도 데이터도 db에 업데이트 해줍니다.
```
=> [feat/room-update_latlng] 경도 위도 userdate_room table에 업데이트 하기

src/components/room/meeting/place/Halfway.tsx, src/components/room/meeting/place/KakaoMap.tsx, src/hooks/useGetHalfway.ts, src/hooks/useMapController.ts, src/utils/place/calcCenterPoint.ts, src/utils/place/convexHull.ts
closed #13 
```
convexHull 알고리즘 이용
무게중심 공식 이용
```
=> [Feature/room-halfway] 중간 지점 보여주기 기능

src/components/room/meeting/calender/CalculateOfMonth.tsx, src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/CheckSelectedDates.tsx
#74
```
1. date-fns를 이용해서 날짜를 담는 로직을 따로 분리했습니다.
2. 일정 미클릭 시 다음 버튼 비활성화시키는 로직 또한 분리했습니다.
```
```
```
다음 버튼 비활성화시키는 로직을 이렇게 따로 빼는 게 맞는지 모르겠습니다.
다른 좋은 방법이 있다면 수정하겠습니다.
더 분리할 수 있는 부분들은 분리해보도록 하겠습니다.
=> [fix/show schedule] 분리할 수 있는 로직 분

src/components/room/meeting/calender/CalculateOfMonth.tsx, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/CheckSelectedDates.tsx, src/components/room/meeting/place/RangeController.tsx, src/hooks/useGetCalendar.ts
```
유저의 캘린더 일정 불러오는 로직을 분리하였습니다
컴포넌트가 아닌 문서의 대문자를 수정하였습니다. 
오타와 상수처리를 구분, 수정했습니다.
```
```
1. 분리하는 과정에서 realtime db를 적용하는 과정 도중 우선 적용사항이 있어 PR을 진행했습니다.
```
=> rename: 상수 대문자로 수정, 캘린더 유저 정보 로직 분리

src/api/room.ts, src/app/room/[id]/page.tsx, src/components/room/StartMeeting.tsx, src/hooks/useSession.ts, src/store/userStore.ts
```
유저 정보 전역 상태 관리, 재사용 supabase 데이터 로직 분리, 유저 정보 가져오는 Loading 상태 만들기 
깜빡임 vs props로  드리릴ㄹ해서 가져오기 깜빡이 승
```
- 방 새로 만들기
- 방 참가하기 방장이 아닌 유저로
- 처음 로그인했을때 유저정보를 가져오는 동안 방 새로만들기 버튼 비활성화
=> [feat] 로그인 유저 관리, 방 생성 참여 리팩토링

src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/EntireOfMonth.tsx, src/components/room/meeting/calender/SchedulesOfIUsers.tsx, src/utils/calendar/calculateOfMonth.ts
closed #88 
```
getCurrentUserData 함수의 위치 if문 안으로 옮겨서 데이터를 불러오는 양을 줄였습니다.
```
```
```
=> [fix/show schedule] getCurrentUserData 함수의 위치 변경

src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/EntireOfMonth.tsx, src/components/room/meeting/calender/SchedulesOfIUsers.tsx
```typescript
const selectedDates = selectedDate.map((date) => {
return {
room_id: id,
created_by: currentUserData.user.id,
start_date: date.toDateString(),
end_date: date.toDateString()
};
});
const supabase = createClient();
const { error } = await supabase.from('room_schedule').insert(selectedDates);
```
선택된 날짜 DB업데이트 한꺼번에 요청하기
[Supabase Docs - Insert Data Bulk create](https://supabase.com/docs/reference/javascript/insert?example=bulk-create)
=> [fix/schedule] 캘린더 컴포넌트 분리, DB업데이트 한꺼번에 요청하기

src/api/place/placeData.ts, src/components/room/meeting/place/KakaoMap.tsx, src/components/room/meeting/place/Place.tsx, src/components/room/meeting/place/RangeController.tsx, src/components/room/meeting/place/search/CategorySelector.tsx, src/hooks/useGetPlace.ts, src/hooks/useMapController.ts, src/store/store.ts, src/types/place.types.ts, src/types/supabase.ts
=> [feat/room search category] 중간 지점 반경 내에 카테고리 검색 결과 보여주기

package.json, src/app/providers.tsx, yarn.lock
```
devtools 버전 react-query랑 맞추기
```
```
TypeError: queryClient.getQueryCache is not a function
```
-> devtools 버전 react-query랑 맞추기
=> [fix/query client] 리액트 쿼리 devtools 업데이트

src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/SchedulesOfIUsers.tsx, src/components/room/meeting/calender/checkSelectedDates.ts
```
날짜 선택 후 장소탭으로 이동했다가 일정 탭으로 돌아오면
날짜 선택을 다시 해야만 다음 버튼이 활성화되어 이 문제를 해결하기 위해
selectedDate를 전역 상태로 관리하려고 시도했습니다.
아직 구현은 되지 않았으나, 머지가 필요해서 pr 올립니다..!
```
```
```
=> [fix/show-schedule]  selectedDate 전역 상태로 관리하려고 시도

src/app/room/[id]/(setting)/layout.tsx, src/app/room/[id]/(setting)/pick-calendar/page.tsx, src/app/room/[id]/(setting)/pick-place/page.tsx
```
room 상단의 단계 표시를 위한 레이아웃만 생성했습니다.
```
```
```
=> [feat/setting-layout] room 레이아웃 생성

src/app/room/[id]/(setting)/pick-place/page.tsx, src/components/room/meeting/place/LocationPicker.tsx, src/components/room/meeting/place/SettingMap.tsx
closed #121
```
pick-place 페이지 생성
기존 KakaoMap 컴포넌트 수정용 지도 사용을 위해 복사 <- 추후 수정용 로직만 사용하기 위해 리펙토링 필요
단계 이동 버튼 생성
```
```
```
=> [feat/pick place] 위치 수정 페이지 생성

src/app/room/[id]/(setting)/FirstStep.tsx, src/app/room/[id]/(setting)/SecondStep.tsx, src/app/room/[id]/(setting)/layout.module.css, src/app/room/[id]/(setting)/layout.tsx, src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/SchedulesOfIUsers.tsx
```
일정과, 장소 페이지가 변경됨에 따라 원이 채워질 수 있도록
stepper를 변경했습니다.
```
```
로직을 어렵게 생각하고 페이지의 url에 따라서 css를 일일히 선택하여 변경하도록
코드를 짜고 있었는데 의찬님의 도움을 받아 더 쉬운 로직으로 변경하여 완성할 수 있었습니다.
```
확정페이지가 아직 존재하지 않아 확정 단계를 눌렀을 때의
경우는 추가하지 않았습니다. 확정 페이지가 생기면 수정하겠습니다.
=> [feat/setting step] stepper를 통해 유저가 진행 단계를 직관적으로 확인 가능하게 구현 

src/components/auth/UserProfileButton.tsx, src/components/room/StartMeeting.tsx, src/hooks/useQueryUser.ts
=> [fix] 유저 가져오는 로직 최종 수정

src/components/auth/MeetingModalButton.tsx, src/components/layout/Header.tsx
#137 
```
클릭시 페이지를 이동하며 모달창을 사라지게 하는 기능이 필요했습니다.
```
```
NextUI를 사용하며 제공되는 기능들을 활용하기 위해 방향성을 변경
```
=> [Feat/modal] 모달창을 클릭시 이동과 함께 창이 사라지는 기능을 추가하였습니다.

src/hooks/useGeoLocation.ts, src/hooks/useSettingMap.ts, src/store/placeStore.ts
closed #130 
```
store persist 적용
roomUsers에서 본인 위치 정보 기반으로 geolocation 실행 
```
```
```
=> [fix/setting place] 내 위치 수정 할 때 기존 저장된 위치 유지하기 기능 수정

src/app/layout.tsx, src/app/providers.tsx
#142 
임시적으로 user 데이터가 Undefined 되는 이슈를 GC infinity 설정으로 해결했습니다.
```
const queryClient = new QueryClient({ defaultOptions: { queries: { gcTime: Infinity } } });
```
```
외않되
```
=> [fix gc]  user 데이터 undefined로 GC되는 이슈 임시 해결

src/hooks/useGetRoomData.ts
#115
```
커스텀 훅 리팩토링, 리액트 쿼리 적용 
```
```
```
=> refactor: 리액트쿼리 적용, 필요없는 로직 제거

src/app/room/[id]/(setting)/confirm/page.tsx, src/app/room/[id]/(setting)/pick-place/page.tsx, src/components/room/meeting/place/LocationPicker.tsx
```
위치 설정 페이지에서 확정 페이지로 이동하는 Link를 Button으로 래핑
위치 설정 페이지 컴포넌트 이름 수정
```
```
```
=> [feat/setting-confirm] 확정 페이지 생성, 위치 설정 페이지와 연결

src/app/page.module.css, src/app/page.tsx, src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx, src/components/room/StartMeeting.module.css, src/components/room/StartMeeting.tsx
closed #137 
```
모달창의 UI와 디자인을 수정하였습니다.
기본적인 페이지의 CSS를 수정하여 기초적인 위치를 변경하였습니다.
```
```
1. NextUI의 버튼 컴포넌트는 submit 타입이 아닌 문제가 존재했습니다.
-타입을 추가하여 문제를 해결하였습니다.
```
=> [style/page] 모달창의 UI와 tailwind CSS를 moduleCSS로 변환, 기본적인 위치 값만의 조정을 진행했습니다.

src/app/globals.css, src/app/layout.tsx, src/app/login/page.module.css, src/app/login/page.tsx, src/app/page.module.css, src/app/page.tsx, src/app/room/[id]/layout.module.css, src/app/room/[id]/layout.tsx, src/app/start/page.module.css, src/app/start/page.tsx, src/components/auth/LoginButton.module.css, src/components/auth/MeetingModalButton.module.css, src/components/auth/MeetingModalButton.tsx, src/components/layout/Header.module.css, src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx, src/components/room/StartMeeting.module.css, src/components/room/StartMeeting.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx, src/components/room/header/user/UserList.module.css, src/components/room/header/user/UserList.tsx, src/components/room/share/LinkShare.module.css, src/components/room/share/LinkShare.tsx
=> [style] 스타일, Next UI 컴포넌트 적용

src/api/supabaseCSR/supabase.ts, src/components/room/meeting/calender/Calender.module.css, src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/EntireOfMonth.tsx, src/store/calendarStore.ts
```
useQuery를 이용하여 시작 날짜, 마지막 날짜를 가져와서 
제한해놓은 범위 외에는 선택할 수 없게 했습니다.
```
```
```
=> [refactor/calendar] 모임 시작하기에서 설정한 범위 외에는 선택 불가하게 구현

src/app/room/[id]/(setting)/layout.module.css, src/app/room/[id]/layout.module.css, src/components/room/meeting/place/ResultMap.tsx, src/components/room/setting/ProgressBar.module.css
```
room layout 넓이 600px 에서 800px로 수정
setting layout 넓이 100%로 상위 넓이에 맞춤
```
```
```
변경전
변경후
=> [fix/style-layout] 설정 페이지 넓이 수정

src/components/auth/UserProfileButton.module.css, src/components/auth/UserProfileButton.tsx, src/components/auth/UserProfileRead.module.css, src/components/auth/UserProfileRead.tsx, src/components/auth/UserProfileUpdate.module.css, src/components/auth/UserProfileUpdate.tsx
=> [Style/profile] 유저 프로필 수정 모달 스타일 변경 1차

src/components/auth/LoginButton.tsx
```typescript
await supabase.auth.signInWithOAuth({
provider,
options: {
redirectTo: `${process.env.NEXT_PUBLIC_PRODUCTION_URL}/auth/callback`
}
});
```
```
배포후 소셜로그인 리다이렉션 로컬호스트로 이동하는 문제
```
[Supabase URL 리다이렉션](https://supabase.com/docs/guides/auth/concepts/redirect-urls)
=> [feat] supabase 로그인 리다이렉션 링크, 배포 링크 환경변수로 설정

src/app/auth/callback/route.ts, src/app/page.tsx, src/components/room/share/KakaoShare.tsx, src/components/room/share/LinkShare.tsx
#92 
```
if (!error) {
return NextResponse.redirect(`${process.env.NEXT_PUBLIC_PRODUCTION_URL}${next}`);
}
```
링크 공유기능 사용하기
=> [feat/share] 룸페이지 링크 공유, import 수정

src/app/auth/callback/route.ts, src/components/room/share/LinkShare.tsx
=> [fix] 배포 로그인 기능

src/app/auth/callback/route.ts, src/components/auth/LoginButton.tsx, src/components/room/share/LinkShare.tsx
=> 배포 로그인 redirectTo URL 가져오는 로직 추가

src/app/auth/callback/route.ts, src/app/page.tsx, src/components/auth/LoginButton.tsx, src/components/room/share/KakaoShare.tsx, src/components/room/share/LinkShare.tsx
=> [deploy] 배포 테스트

src/components/auth/LoginButton.tsx
#159 
#3 
> 배포문제로 지웠던 로그인 콜백url 을 삭제해서 로그인이 바로 안되는 문제 수정
> 멍청이
배포하고 로그인하기
=> [fix] 로그인 콜백 배포문제로 지운거 복구

src/app/auth/signout/route.ts, src/components/auth/LogoutButton.tsx
=> [feat] /auth/signout 요청 라우트 핸들러로 로그아웃하기

src/api/room.ts, src/api/supabaseCSR/supabase.ts, src/app/room/[id]/(setting)/confirm/page.tsx, src/components/room/meeting/calender/Calender.tsx, src/hooks/useMutateUserData.ts, src/store/calendarStore.ts, src/types/roomUser.ts, src/utils/sortDate.ts
```
저장 버튼 클릭시 db에 일정, 장소 올리기
```
```
```
=> feat: 룸 설정 확정 기능 생성

src/app/room/[id]/(setting)/confirm/page.tsx
```
설정 저장을 할 때 session storage에 저장하던 설정 값들을 지워준다.
```
```
```
=> [fix/session-storage] 저장시 session storage clear

src/api/supabaseCSR/supabase.ts, src/app/login/page.module.css, src/app/login/page.tsx, src/components/auth/LoginButton.module.css, src/components/auth/PayPalDonate.module.css, src/components/auth/PayPalDonate.tsx, src/components/my-owl/meeting/Meeting.tsx, src/components/room/StartMeeting.module.css, src/components/room/StartMeeting.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx, src/components/room/header/user/UserList.module.css, src/components/room/header/user/UserList.tsx, src/components/room/meeting/place/LocationPicker.tsx, src/components/room/share/KakaoShare.tsx, src/components/room/share/LinkShare.tsx, src/hooks/useGetRoomUsers.ts
룸페이지 레이아웃, 공유링크 디자인 수정, 유저 가져오는 로직 안쓰는 함수 바꾸기, 참여중인 모임이 없다는 표시 추가
=> [style] 룸페이지 헤더 스타일 수정

src/components/header/UserProfileButton.module.css, src/components/header/UserProfileButton.tsx, src/components/header/UserProfileRead.module.css, src/components/header/UserProfileRead.tsx, src/components/header/UserProfileUpdate.module.css, src/components/header/UserProfileUpdate.tsx, src/components/my-owl/profile/modal/Modal.module.css, src/components/my-owl/profile/modal/Modal.tsx
closed #133 
#135 
next UI 및 module css 를 활용하여 스타일을 전반적으로 수정했습니다.
또한, 유저 프로필 조회 화면에 로그아웃 버튼을 추가했습니다.
<br/>
=> [Style/profile] 유저 프로필 설정 버튼 및 모달 디자인 전반적으로 수정, 누락 기능 추가 완료

src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx
=> [Stye/header meeting]

src/components/auth/LogoutButton.module.css, src/components/auth/LogoutButton.tsx, src/components/header/Header.tsx, src/components/header/MeetingModalButton.module.css, src/components/header/MeetingModalButton.tsx, src/components/header/UserProfileButton.module.css, src/components/header/UserProfileButton.tsx, src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx, src/components/room/header/user/UserList.module.css, src/components/room/header/user/UserList.tsx
=> [Style/header] 헤더와 관련된 디자인 전반적으로 수정

src/components/room/meeting/calender/Calender.tsx, src/components/room/meeting/calender/EntireOfMonth.tsx
=> [feat/blockSelect]: 방장이 설정한 범위를 제외한 날짜들 모두 회색으로 표시

src/app/globals.css
=> style: 웹페이지 전체 폰트 적용

package.json, src/api/room.ts, src/app/room/[id]/page.module.css, src/app/room/[id]/page.tsx, src/components/room/ConfirmedButton.module.css, src/components/room/ConfirmedButton.tsx, src/components/room/StartMeeting.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx, src/components/room/header/user/UserList.tsx, src/components/room/meeting/ResultPlace.module.css, src/components/room/meeting/ResultPlace.tsx, src/components/room/meeting/calender/ResultSchedule.module.css, src/components/room/meeting/calender/ResultSchedule.tsx, src/components/room/meeting/place/RangeController.module.css, src/components/room/meeting/place/RangeController.tsx, src/components/room/meeting/place/ResultMap.module.css, src/components/room/meeting/place/ResultMap.tsx, src/components/room/meeting/place/search/CategorySelector.module.css, src/components/room/meeting/place/search/CategorySelector.tsx, src/components/room/meeting/place/search/SearchBar.tsx, src/hooks/useMapController.ts, src/utils/mostSchedule.ts, yarn.lock
모임 현황 페이지에서 모임 참가자들이 선택한 날짜들을 많은 참가자들이 선택한 순서로 보여주고 내 일정과 장소를 수정할 수 있는 링크, 현재 중간지점을 기반으로 카테고리 등등등 레이아웃 디자인 조금씩 더 추가할거임
디자인 모르겠따 생각나는대로 스타일 지정함
- 방장만 모임 확정 버튼
- 모임이 확정되었으면 다시 확정 X
=> [feat] 모임 현황 페이지 확정

src/components/header/UserProfileRead.module.css
=> [style] 유저 소셜 로그인 정보 아이콘 ui 수정

src/app/page.module.css, src/components/Footer.tsx, src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx
=> [Style/changeunit]

src/components/room/StartMeeting.module.css, src/components/room/StartMeeting.tsx
=> [style] start 페이지 스타일

src/store/placeStore.ts
closed #199 
```
range 초기값 300 에서 200 수정
```
```
```
=> [fix/default-range] range 단위 변경으로 인해 store에서 초기값 수정 300 -> 200

src/app/room/[id]/(setting)/confirm/page.tsx
```
기존 upsert시 덮어씌우기가 적용 안되고 새로운 row를 생성 되어 기존 사용하던 update로 변경
schedule은 handleSubmit이 실행 되면 db의 해당 room, user의 schedule row 들을 리셋하고 새로 설정한 scehdule이 등록 되게 수정
```
```
```
=> [fix/confirm] setting/confirm의 upsertRoomUser, upsertSchedule 수정

src/app/room/[id]/(setting)/confirm/page.tsx, src/components/room/meeting/calender/ResetSchedule.tsx, src/hooks/useMutateUserData.ts
```
resetUserScheduleDB의 비동기 작업을 동기 작업으로 수정하기 위해 useMutation의 mutate를 mutateAsync로 수정
```
```
```
=> [fix/setting-confirm] handleSubmit에서 schedule DB에 reset하는 로직 동기 작업으로 수정

src/app/room/[id]/(setting)/confirm/page.tsx, src/app/start/(create)/confirm/page.tsx, src/components/room/meeting/place/RangeController.tsx
#195
update를 upsert로 수정하고 upsert할 수 있도록 DB Primary 키 수정
```typescript
const { data, error } = await supabase.from('userdata_room').upsert([{ ...userData }]);
```
Supabase 테이블에서 유저아이디 룸아이디 row아이디 총 3개가 Primary키로 등록되어있어  유저아이디와 룸아이디로만 upsert
로 update가 안되고 새로운 row가 추가되는 현상 -> 유저아이디와 룸아이디만 primary키로 등록
- [supabase upsert](https://supabase.com/docs/reference/javascript/upsert)
유저가 새로운 모임에 입장해서 일정과 장소를 등록하면 모임에 유저가 추가되어야 함
=> [fix] 기존 모임에 새로운 유저가 추가되지 않던 문제 수정

src/components/room/meeting/place/GeolocationButton.module.css, src/components/room/meeting/place/GeolocationButton.tsx, src/components/room/meeting/place/ResultMap.module.css, src/components/room/meeting/place/SettingMap.tsx, src/components/room/meeting/place/search/SearchBar.tsx, src/components/room/meeting/place/search/SearchIcon.tsx, src/hooks/useGeoLocation.ts, src/hooks/useGetRoomUsers.ts, src/hooks/useSettingMap.ts, src/store/roomUserStore.ts
=> [fix/setting-place] 유저 위치 설정 할때 DB에 저장된 기존 위치 유지하기, 이동한 위치 검색바 placeholder에 보여주기, gps위치 수정

src/components/room/Dashboard.tsx, src/components/room/meeting/calender/ResultSchedule.module.css, src/components/room/meeting/calender/ResultSchedule.tsx
일정이 하나도 없을 때 모임 현황 페이지에서 내 일정 변경하기 링크가 밖으로 나가는 문제 수정
이전에 사용하던 position: absolute로 위치를 지정하던 것을 제거
=> [fix/dashboard] 내 일정 변경하기 링크 UI 밖으로 나가는 문제 수정

src/app/page.module.css, src/app/room/[id]/layout.tsx, src/components/room/meeting/place/SettingMap.tsx
투두리스트 참고 
```
```
지도 줌 레벨 바꿔보기
=> [feat] 지도 최소 레벨 지정

src/components/auth/LogoutButton.module.css, src/components/header/Header.tsx, src/components/header/profile/UserProfileButton.module.css, src/components/header/profile/UserProfileButton.tsx, src/components/header/profile/UserProfileRead.module.css
closed #225 
UX를 고려하여 UI, CSS 수정하였습니다.
=> [style/head] 프로필 조회 및 로그아웃을 드롭다운 메뉴로 통합, 모임 방 조회 아이콘 위치 오른쪽으로 수정

src/components/room/place/LocationSwitch.tsx, src/components/room/place/SettingMap.module.css, src/components/room/place/SettingMap.tsx, src/hooks/useGeoLocation.ts, src/hooks/useSettingMap.ts, src/types/place.types.ts
```
roomUser 데이터의 startLocation 값을 boolean형 변환 하여 isPinned 변수에 할당 --> 위치 지정 토글 상태 관리
isPinned 값에 따라 위치 지정용 Pin과 유저 프로필 Pin을 보여줄지 결정
첫 페이지 마운트 시 startLocation 값 유무에 따라 gps 자동 연동
```
```
```
=> [fix/location-switch] 위치 지정 Pin 버튼 토글기능, 중앙 위치 지정 Pin 토글 기능, gps 자동 연동 시점 수정

src/app/page.tsx, src/components/rending/StartMeetingBtn.module.css, src/components/rending/StartMeetingBtn.tsx, src/components/room/StartMeeting.tsx, src/hooks/useMapController.ts
closed #229 
이벤트 최적화를 위해 랜딩 페이지 및 방 생성 페이지의 버튼에 throttling처리를 하여 서버 부하를 줄였습니다.
통일성을 위해 lodash 라이브러리를 이용하여 구현하였습니다.
**[개념]**
- https://velog.io/@nowod_it/Javascript-debounce%EC%99%80-throttle
- https://velog.io/@letthere/developic-Lodash-throttle-debounce
[적용]
- lodash 라이브러리와 [useCallBack](https://react-ko.dev/reference/react/useCallback)
- [useCallBack 더보기](https://velog.io/@hnsoo/useCallback-%EC%A0%95%EB%A6%AC)
- https://velog.io/@leejpsd/Lodash
=> [fix/optimize] 서버 부하 줄이기 : 이벤트 최적화를 위한 throttling처리

src/components/room/StartMeeting.tsx, src/components/room/sidebar/user/UserList.tsx
모임 생성버튼 누르고 모임페이지로 이동할 때까지 버튼 로딩 표시, 모임 생성 후 뒤로가기 하면 메인페이지로 이동. push -> replace
모임에 없는 유저가 링크로 접속하면 새로운 유저 추가 
- 모임생성버튼으로 모임생성
- 새로운 모임 링크로 접속하면 모임에 유저 추가
=> [feat] 모임 페이지에 접속하면 유저 추가하기

src/components/header/profile/UserProfileButton.tsx, src/components/header/profile/UserProfileRead.tsx, src/components/header/profile/UserProfileUpdate.tsx
이미지 업로드 안되는 에러, 닉네임 변경사항 적용 안되는 에러 임시 해결
=> [fix] 이미지 업로드 안되는 에러, 닉네임 변경사항 적용 안되는 에러 임시 해결

src/components/header/MeetingModalButton.module.css, src/components/header/MeetingModalButton.tsx, src/components/header/profile/UserProfileButton.module.css, src/components/my-owl/meeting/Meeting.module.css, src/components/my-owl/meeting/Meeting.tsx, src/components/my-owl/profile/modal/Modal.module.css, src/components/my-owl/profile/modal/Modal.tsx
closde #241 
closed #242 
TODOLIST와 이하동문입니다.
- https://velog.io/@cmaw/typescript-input-typefile-image-preview-%EB%AF%B8%EB%A6%AC%EB%B3%B4%EA%B8%B0nextJs-React
- https://developer.mozilla.org/ko/docs/Web/API/FileReader
=> [style/header] 프로필 수정 화면에서 파일 업로드 시 사진 미리보기 구현, 모임 방 리스트 모달 크기 및 애니메이션 변경, verified 로고 보여주기, 기타 CSS 작업

src/components/room/place/LocationSwitch.module.css, src/components/room/place/LocationSwitch.tsx
```
디자인에 맞춰 toggleState에 따른 아이콘 종류 분기 렌더링이 아니라 style을 변경해 아이콘 배경이 바뀌게끔 변경
```
```
```
=> [style/locationSwitch]: 위치 지정 토글 style 변경

src/components/room/sidebar/user/UserCard.module.css, src/components/room/sidebar/user/UserCard.tsx
=> [style] userList의 border 스타일 변경

src/app/providers.tsx, src/components/room/place/search/SearchBar.tsx, src/hooks/useGetRoomUsers.ts, src/hooks/useMapController.ts, src/hooks/useQueryPlace.ts, src/hooks/useQueryRoomUsers.ts, src/hooks/useSettingMap.ts
```
```
```
```
- [useQuery 기본 문법 1. queryKey](https://github.com/ssi02014/react-query-tutorial?tab=readme-ov-file#usequery-%EA%B8%B0%EB%B3%B8-%EB%AC%B8%EB%B2%95)
=> [fix/query] query 함수 이름 변경, queryKey kebab-case로 변경

src/components/room/ConfirmedButton.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx
```
```
```
방제목 위에 방장 이름까지 표시하려고 하였으나, 실패했습니다.
내일 다시 도전할 계획입니다....
```
=> [style/room title] 방제목 스타일 변경

src/hooks/useQueryPlace.ts
```
주소 변환, 검색, 카테고리 검색 queryKey 각각 ['address',location], ['search-keyword',searchKeyword], ['search-category', searchOption] 으로 변경
위 쿼리들 gcTime 300,000ms 5분으로 설정
```
```
```
=> [fix/useQueryPlace] queryKey이름, gcTime 5분으로 변경

src/components/room/place/LocationSwitch.module.css, src/components/room/place/LocationSwitch.tsx, src/components/room/place/SettingMap.module.css, src/components/room/place/SettingMap.tsx, src/components/room/place/StartLocationBox.module.css, src/components/room/place/StartLocationBox.tsx, src/components/room/sidebar/Sidebar.tsx
```
위치 지정 box 생성, 위치 고정 버튼 위치 변경, 위치 지정 Pin 그림자 추가
```
```
```
=> [feat/location-box] 위치 지정 box 생성, 위치 고정 버튼 위치 변경, 위치 지정 Pin 그림자 추가

src/components/room/place/search/SearchBar.tsx
```
"X" 아이콘 추가하여 X 클릭 시 검색어가 초기화될 수 있게 수정했습니다.
```
```
```
=> [feat/search bar] "X" 아이콘 추가하여 검색어 초기화

src/app/page.module.css, src/app/page.tsx, src/components/Footer.module.css, src/components/Footer.tsx, src/components/rending/Article.module.css, src/components/rending/Article.tsx
랜딩 페이지 스타일을 변경하였습니다. 
아티클 내용의 경우, 편집하기 쉽도록 컴포넌트 화 하였습니다.
아티클의 내용은 1차 수정만 완료된 단계이고, 추후 내용 및 디자인(\n등) 수정이 필요합니다.
=> [style/landing] 랜딩 페이지 스타일 변경

src/components/room/header/RoomHeader.tsx, src/components/room/place/StartLocationBox.module.css, src/components/room/place/StartLocationBox.tsx, src/components/room/share/LinkShare.module.css, src/components/room/share/LinkShare.tsx, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/Sidebar.tsx, src/components/room/sidebar/user/UserCard.tsx
```
1. 출발 위치 확정 전/후 안내 문구를 직관적으로 변경했습니다.
2. 모임방 링크 공유하기 버튼을 추가했습니다.
3. 사이드바의 스크롤바를 생성했습니다.
```
```
```
공유하기 버튼은 추후에 아이콘/문구를 수정해도 좋을 것 같습니다.
=> [style/sidebar-ux] 

src/app/room/[id]/page.module.css, src/app/room/[id]/page.tsx, src/components/room/place/SettingMap.tsx, src/components/room/sidebar/MyRooms.tsx, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/Sidebar.tsx, src/components/room/sidebar/ToggleSidebar.module.css, src/components/room/sidebar/ToggleSidebar.tsx
가로폭이 800px 이하는 사이드바가 지도 위로 올라옴. 800px 이상은 사이드바 영역만큼 지도가 밀림.
사이드바 열고 닫기
=> [style/sidebar] 사이드바 열고 닫기

src/api/supabaseCSR/supabase.ts, src/app/room/[id]/page.module.css, src/app/room/[id]/page.tsx, src/components/room/calender/Calender.tsx, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/Sidebar.tsx
방 유저 수 실시간 반영하여 데이터 전달하여 달력 스타일 문제 해결, 스크롤 바 디자인 변경하였습니다.
=> [style/sidebar] 유저 수 실시간 반영, 스크롤 바 디자인 변경

src/components/room/place/HalfwayButton.tsx, src/components/room/sidebar/user/UserCard.module.css, src/components/room/sidebar/user/UserCard.tsx, src/components/room/sidebar/user/UserList.tsx, src/hooks/useGetRoomUsers.ts
= 투두리스트
```typescript
useEffect(() => {
if (!isPending) {
const isExistUser = roomUsers.some((user) => user.user_id === userId);
if (!isExistUser) {
joinNewUser();
}
}
}, [isPending]);
```
챗지피티가 user_id를 id로 가져왔어요
위치가 지정된 유저리스트 클릭
=> [feat/viewpoint] 유저리스트 위치이동, 중심위치 이동

src/app/room/[id]/page.module.css, src/components/header/profile/UserProfileUpdate.tsx
=> [fix] 새로고침이 모달 창 수정 화면을 띄웠을 때만 경고를 표시하도록 수정하였습니다.

src/app/room/[id]/page.module.css, src/app/room/[id]/page.tsx, src/components/room/calender/EntireOfMonth.tsx, src/components/room/header/RoomHeader.module.css, src/components/room/header/RoomHeader.tsx, src/components/room/place/HalfwayButton.module.css, src/components/room/place/HalfwayButton.tsx, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/Sidebar.tsx, src/utils/calendar/dayColors.ts
1. 중심 위치에 맞게 지도를 포커싱해주는 버튼을 연결했습니다.
2. nav바는 고정하고, 오른편의 사이드바만 움직일 수 있게 했습니다.
```
```
=> [style/sidebar] 중심 위치 주소 버튼 연결, navbar 고정

src/app/auth/delete/route.ts
```
```
```
기존 axios post 요청을 할때 data를 formData로 넣어줬는데 https://oauth2.googleapis.com/revoke?token=TOKEN 형식으로 요청을 보내야해서 params 옵션으로 수정
=> [fix/auth-delete] google revoke request config params 수정

src/components/room/chatRoom/InputBox.tsx, src/components/room/chatRoom/Message.tsx, src/store/messageStore.ts, src/types/supabase.ts
=> [Feat] message 테이블에서 name 컬럼을 추가하였기 때문에 로직을 변경합니다.

src/app/globals.css, src/app/providers.tsx, src/app/room/[id]/page.module.css, src/components/room/chatRoom/ChatRoom.module.css, src/components/room/place/SettingMap.module.css, src/components/room/place/SettingMap.tsx, src/components/room/place/StartLocationBox.module.css, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/user/UserCard.module.css
사이드바 리렌더링 너무 빨리 되어서 맵 빈부분 생기는 문제 수정. 모바일 반응성 향상 
```typescript
useEffect(() => {
setTimeout(function () {
mapRef.current?.relayout();
}, 300);
}, [isOpened]);
```
transition 시간 0.3초에 맞춰서 setTimeout 지정
=> [style] 모임페이지 스타일 수정, 맵 리렌더링 딜레이

src/api/auth/signInWithOAuth.ts, src/app/install/page.tsx, src/app/room/[id]/page.module.css, src/app/start/layout.module.css, src/app/start/layout.tsx, src/components/InstallAppButton.tsx, src/components/auth/LoginButton.tsx, src/components/room/place/LocationSwitch.module.css, src/components/room/sidebar/Sidebar.module.css, src/components/room/sidebar/user/UserCard.module.css, src/components/room/sidebar/user/UserCard.tsx, src/components/room/sidebar/user/UserList.module.css, src/components/room/sidebar/user/UserList.tsx, src/middlewares/protectRoute.ts, src/utils/getCallbackURL.ts
=> [feat/style] 로그인하면 이전 페이지로 이동,  PWA 앱설치 페이지, 사이드바 스타일

src/components/room/place/Halfway.module.css, src/components/room/place/Halfway.tsx
```
Mapmarker 를 CustomOverlayMap으로 변경하여 z-index 속성을 부여했습니다.
```
```
```
=> [style/halfway-marker] 유저마커와 중간지점 마커 겹치는 문제 해결

src/app/room/[id]/confirm/page.module.css, src/app/room/[id]/confirm/page.tsx, src/components/room/header/ResultHeader.module.css, src/components/room/header/ResultHeader.tsx, src/components/room/place/ResultMap.module.css, src/components/room/place/ResultMap.tsx, src/components/room/place/search/CategorySelector.module.css, src/components/room/place/search/CategorySelector.tsx, src/components/room/share/LinkShare.module.css
```
의미 없는 fragment 삭제
페이지 container  : position relative
지도, 헤더, 카테고리 : absolute
컨텐츠들 지도 위로 올라오게 스타일 수정
```
```
```
=> [fix/result page] 페이지 무분별한 fragment 삭제, 페이지 스타일 수정

src/components/room/header/ResultHeader.tsx, src/components/room/header/RoomHeader.tsx, src/components/room/place/ResultMap.tsx, src/components/room/place/search/CategorySelector.tsx, src/hooks/useMapController.ts, src/hooks/useQueryPlace.ts
=> [fix/result-map] 최종 페이지에서 중심지점 주소를 눌렀을때 이동기능 추가, 카테고리 선택 전에 query요청 취소

src/components/my-owl/meeting/Meeting.tsx, src/components/my-owl/meeting/MeetingIsPending.module.css, src/components/my-owl/meeting/MeetingIsPending.tsx
정보 불러오는 미팅 모달의 로딩 화면 문구를 사진과 같이 변경했습니다.
=> [style/meetingmodal] 방 정보 불러오는 로딩 화면 문구 변경

package.json, src/app/room/[id]/page.tsx, src/components/loading.module.css, src/components/loading.tsx, src/components/room/ConfirmedButton.tsx, src/components/room/chatRoom/InputBox.tsx, yarn.lock
```
1.채팅룸에서 마지막 글자가 두 번씩 반복되는 가장 큰 이유는 한글은 컴포징 단계를 거치기 때문입니다. 
따라서 채팅이 전송되는 조건에 isComposing 이벤트를 추가로 필터하여 적용시키는 부분이 존재했습니다.
2. 방장이 확정페이지에서 뒤로가기 버튼을 통해 룸 페이지로 돌아올 수 있는 버그가 존재하였습니다.
- 이 부분은 라우터가 다른 컴포넌트에서 동작하기 때문에 발생한 문제이고 이 문제를 통해 
ConfirmButton 컴포넌트에서 라우터 푸시를 하는 부분이 존재한다는 것을 찾을 수 있었습니다. 
따라서 ConfirmButton 컴포넌트에서는 정보의 갱신만을 하도록 나누고 SettingPage 컴포넌트에서 라우터를 replace하는 것으로 문제를 
처리했습니다.
3. 정보를 갱신 할 때 사용하는 방식으로는 useQuery를 이용하고 있었기 때문에 정보의 반영이 필요했습니다.
- 필터에서 사용하는 것은 room의 isVerified의 bool값이 있었는데, 이것을 적용시키기 위해 invalidateQueries를 사용하였습니다.
4. framer-motion 라이브러리가 추가되었습니다. 
- 새로운 라이브러리를 yarn을 통해 최신화해주세요
```
```
1. 처음 채팅이 두 번 써는 이슈가 존재할 때는 특정 기기에서만 발생했기 때문에 채팅의 최소 딜레이를 부여했습니다.
- 하지만 이 부분이 완벽한 해결이라고 여겨지지 않아 정보를 탐색, 
isComposing이라는 키보드 이벤트가 존재한다는 것을 알아냈습니다. 
따라서 이 옵션을 필터하여 채팅을 보다 오류없이 주고 받을 수 있게 제작하였습니다. …
```
=> [Feat/loading screen] 라우터를 confirm button 컴포넌트가 아닌, settingPage에서 지정하도록 수정, 채팅 룸 버그 수정

src/components/room/chatRoom/ChatRoom.tsx, src/components/room/chatRoom/InputBox.module.css, src/components/room/chatRoom/ListMessage.module.css, src/components/room/chatRoom/ListMessage.tsx, src/components/room/chatRoom/Message.module.css, src/components/room/chatRoom/Message.tsx, src/components/room/sidebar/Sidebar.tsx
=> [style/chat room] 채팅방 스타일 변경

src/api/place/placeData.ts, src/components/room/ConfirmedButton.tsx, src/components/room/header/ResultHeader.tsx, src/components/room/header/RoomHeader.tsx, src/components/room/place/HalfwayButton.tsx, src/components/room/place/search/CategorySelector.tsx, src/hooks/useMapController.ts, src/hooks/useQueryPlace.ts, src/hooks/useSettingMap.ts, src/store/halfwayStore.ts
```
ResultHeader에서 주소,날짜를 rooms 테이블에서 가져온 data로 수정
halfway 전역 스토어에서 lat,lng를 halfwayPoint에 중첩
location을 address로 변경
store 내용 수정하면서 참조파일에 타입, 변수 등 변경점 적용
```
```
useEffect안에서 halfwayPoint의 유무로 조건문을 작성
halfwayPoint 는 {lat,lng}의 참조형 데이터이므로 항상 true 상태여서 조건에 걸리지 않아 리렌더링이 일어나는 수 만큼 발생
조건을 halfwayPoint.lat, halfwayPoint.lat 내부 데이터의 유무로 변경
```
=> [fix/place] 중간지점 주소를 db에 null로 보내는 문제 해결, halfwayDataStore의 state,action 수정

src/app/room/[id]/confirm/page.tsx, src/components/room/header/ResultHeader.tsx, src/components/room/place/ResultMap.tsx, src/components/room/place/search/CategorySelector.tsx, src/hooks/useMapController.ts, src/hooks/useQueryRoomData.ts, src/hooks/useQueryRoomUsers.ts, src/hooks/useSettingMap.ts
=> [fix/place] getRoomData react-query적용, 확정 페이지에서 중간지점 정보들 react-query로 가져온 값으로 변경

src/components/room/place/search/CategoryMarker.tsx
```
CustomOverlayMat zIndex MapMarker보다 상위로 수정
```
```
```
=> [style/categoryInfo] 카테고리 정보 zIndex 수정

src/components/room/ConfirmedButton.tsx, src/components/room/calender/ResetSchedule/ResetSchedule.tsx, src/components/room/chatRoom/ChatRoom.tsx, src/components/room/header/RoomHeader.tsx, src/components/room/place/HalfwayButton.tsx, src/components/room/share/LinkShare.tsx, tailwind.config.ts
=> [style/sidebar] 사이드바 디자인 수정

src/app/room/[id]/page.module.css, src/components/loading.module.css, src/components/room/chatRoom/ChatRoom.module.css, src/components/room/chatRoom/ChatRoom.tsx, src/components/room/place/LocationSwitch.module.css, src/components/room/place/StartLocationBox.module.css
=> [fix/setting-map] 출발 위치 지정 UI 수정, 채팅 버튼 위치 수정

public/images/category_marker.svg, src/components/room/place/Halfway.tsx, src/components/room/place/search/CategoryIcons.tsx, src/components/room/place/search/CategoryMarker.tsx, src/components/room/place/search/CategorySelector.tsx
```
카테고리 아이콘은 svg 컴포넌트로 만들어 CategoryIcons.tsx 파일에 모아서 관리
MapMarker는 이미지 경로로 사용해야해서 Public에 svg파일 저장
```
```
```
=> [fx/icons] 새로 받은  icon, marker svg로 수정

src/components/room/place/SettingMap.module.css, src/components/room/place/StartLocationBox.module.css, src/components/room/place/search/SearchBar.module.css, src/components/room/place/search/SearchResultList.module.css
=> style: z-index 수정
