where-we-meet/owl

src/app/my-owl/page.tsx
src/components/my-owl/meeting/Meeting.module.css
src/components/my-owl/meeting/Meeting.tsx

closed #8 #9 
```
모임 컨테이너 클릭 시, 프로필 수정 중에 있었다면 유저에게 변경사항 저장을 물어보기 는 
상태 관리 위치를 바꾸어야 하므로, feature/myowl-profile branch merge 이후에 구현이 가능합니다. 
```
```
- 현재까지 제공된 와이어프레임을 기준으로 기본적인 UI 틀을 만들었습니다. 
- overflow-y:scroll 속성을 적용했습니다.
- 유저가 참여하고 있는 모임 방에 대한 정보들을 가져오는 로직을 useEffect로 구현하였습니다.
- 모임 방 컨테이너 클릭 시, 해당 모임 방으로 이동하도록 구현하였습니다. 
- useRouter() : next/navigation을 사용하였습니다.
- created_at과 verified을 기준으로 meetingInfo를 정렬하는 함수를 만들었습니다. 
정렬 우선순위는 아래와 같습니다.
- 1순위 : verified가 true
- 2순위 : created_at이 가장 빠른 날짜
```
```
전반적으로 비동기 처리와 관련하여 Type에 대한 문제가 많았습니다. 
현재는 기능을 구현하는 것 자체가 우선순위라 시간 단축을 위해 GPT에게 많은 힌트를 얻어 문제를 해결 하였는데, 
추후 리팩터링을 하며 제 스타일이 잘 드러나는 코드로 개선하고 싶네요.
```
1. [promise.all()](https://velog.io/@jay2u8809/Promise.all-%EB%A1%9C-%EB%B9%84%EB%8F%99%EA%B8%B0-%EC%B2%98%EB%A6%AC%EB%A5%BC-%EA%B5%AC%ED%98%84% …

[feat/meeting] 모임 방 정보 조회 및 이동 구현

---

src/api/supabase.ts
src/app/room/[id]/page.tsx
src/components/room/sidebar/user/UserList.tsx
src/utils/supabase/userDataFetch.ts

#18 
```
realtime db를 사용시 클린업으로 구독을 해지하는 기능을 삽입하는 것이 권장됩니다. 따라서 기존 로직을 분리하였습니다. 
또한 직관적인 타입을 위하여 Users 타입의 이름을 RoomData로 변경하였습니다.
realtime을 적용하여 userdata_room의 데이터를 반영할 수 있게 되었습니다.
```
```
현재 realtime db를 사용하며, 적용하는 부분에 있어서 어려움을 겪고 있습니다.
```
realtime db에서 필요한 기능 중, 변동사항을 payload를 콜백함수로 가져 올 수 있는데 이 기능에 대해서 조금 더 공부가 필요 할 것 같습니다.

[feat/userlist] realtime db를 적용하기 위하여 비즈니스 로직을 분리, 타입 이름을 직관적으로 변경

---

src/components/my-owl/profile/Profile.tsx
src/components/my-owl/profile/editable/UserInfo.tsx
src/components/my-owl/profile/editable/modal/Modal.module.css
src/components/my-owl/profile/editable/modal/Modal.tsx

closed #7 
```
- 링크 첨부 로직은 아직 구현되지 않았습니다. 
- 프로필 사진의 경우, 취소 버튼 클릭 시 이전 프로필 사진이 적용되지 않습니다. 
구현을 위해 임시 state를 마련했으나, 아직 활용하지 못했습니다. 
- 위 두가지의 미구현 기능은 supabase 관련된 코드가 정리 된 이후에 구현하도록 하겠습니다.
가장 급한 기본 기능 우선 구현했으니 참고 부탁드립니다.
```
```
1. Modal.tsx 파일을 생성하여 아래의 기능들을 구현하였습니다.
- 용량 확인용 byte 변환기 byteCalculater
- 파일 용량 제한 로직 handleFileMaxSize
- 파일 이름 중복 방지용 파일 이름 생성 로직 getFileName
- supabase store 이미지 업로드 로직 uploadImage
- 유저 프로필 사진 업데이트 로직 changeUserProfile
```
1. `uploadImage`가 작동하지 않는다?
**[문제상황]**
다음 태그 내에서 `사진 업로드하기` 버튼을 눌렀을 때, supabase store로 사진이 업로드 되어야 하는데, 동작하지 않는 문제가 발생했다.
```html
<form>
<input type="file" accept="image/jpeg,image/png,image/jpg" onChange={handleFileMaxSize} />
<button disabled={fileSizeExceed} onClick={handleUploadImage}>
사진 업로드하기
</button>
</form>
```
**[원인파악]**
form태그로 감싸져 …

[feat/profile] 유저 프로필 사진 수정 기능 구현

---

src/app/login/page.module.css
src/components/layout/Header.tsx

#55
```
const headersList = headers();
const fullUrl = headersList.get('referer') || '';
if (fullUrl.split('/')[3] === 'login') return null;
```
다른페이지에서 로그인페이지로 이동하면 header 서버 컴포넌트는 그대로 가져오기때문에 변경되지 않음.
그냥 `position absolute`로 덮어씌우기
로그인페이지에서 헤더 메뉴 보이는지 테스트

fix: 로그인 페이지 헤더 숨기기

---

src/components/room/meeting/place/KakaoMap.tsx
src/components/room/meeting/place/LocationPicker.tsx
src/components/room/meeting/place/search/SearchResultList.tsx
src/hooks/useCenterState.ts
src/hooks/useGetPlace.ts
src/hooks/useMapController.ts
src/store/store.ts
src/utils/place/dragCenter.ts

closed #47 
```
초기 현재 유저의 위치 정보를 가져올 때 시간이 걸림
=> pin 위치에 임시로 loading... 문구 적용 / 추후에 스피너로 대체 하면 좋을 것 같음
const userLocationData = useSearchDataStore((state) => state);
=> store에서 유저의 위치 정보를 가져옵니다. (location, address, addressName)
const setLocation = useSearchDataStore((state) => state.setLocation);
const setAddress = useSearchDataStore((state) => state.setAddress);
=> store에서 위치와 주소 state를 변경할 setter 함수를 가져옵니다.
useMapController 커스텀 훅으로 서비스 로직 분리
```
```
지도가 움직이면 중심이 실시간으로 바뀌어 위치 값 state가 변경됨 => 위치 관련된 컴포넌트 리렌더링
=> debounce 사용하여 최종의 위치값만 set state 함
debounce를 적용했다보니 드래그를 하다가 잠시 멈춰 있으면 위치값이 변하지 않아 위치 값이 set state 되고 현재 위치 기반의 주소를 fetch 해옴
=> drag 상태값을 사용하여 useQuery enabled 옵션에 location 값 유무와 drag 상태를 비교하여 data fetching 함
```
새로운 버그가 있다면 이슈를 만들어주세요 ㅜㅜ

[Fix/room-set_location] 검색 결과 선택 외 방법으로 유저 위치 값 못 가져오는 이슈 수정, 유저 위치 초기에 pin에 loading 표시

---

src/app/room/[id]/page.tsx
src/components/room/meeting/place/KakaoMap.tsx
src/components/room/meeting/place/UserMarker.tsx
src/components/room/sidebar/Sidebar.tsx
src/components/room/sidebar/user/UserList.tsx
src/hooks/useGetRoomData.ts
src/store/store.ts
src/types/roomUser.ts

closed #63 
```
useGetRoomData의 roomUser 지역 상태 전역 상태로 변경하면서 관련 prop drilling 및 import 경로 수정
store 에서 가져온 roomUsers 데이터로 지도에 유저들 선택한 위치 marker 표시
아직 유저가 위치를 지정하면 설정용 pin UI 제거는 못함
```
```
useGetRoomData의 useEffect 안에서  store에서 가져온 roomUsers에 realtime으로 구독한 payload.new를 가공해 newRoomUsers를 만들어 setRoomUsers(newRoomUsers) setter 함수를 사용해 state를 변경하려했지만 roomUsers가 초기값 빈배열로만 나와 업데이트가 안되는 상황이 발생
=> zustand store에서 변경된 payload.new를 가져와 state를 변경하면서 해결
```

[Feature/room-user_marker] 지도에 유저들 위치 marker 표시, roomUsers 전역 관리

---

src/hooks/useGetHalfway.ts
src/types/place.types.ts
src/utils/place/calcCenterPoint.ts
src/utils/place/convexHull.ts

closed #75 
```
util 함수 반환 타입 맞추기
변경된 타입 수정 및 적용하기
```
```
초기에 calcCenterPoint 함수에서 반환된 result의 lat, lng 값을 의존성 배열의 변수로 넣어 사용하고 있습니다.
calcCenterPoint에서 계산할 매개변수가 없을 경우 빈 return으로 함수를 종료 하여 result의 타입이 {...} | undefined로 추론됩니다.
의존성 배열에서 [ result?.lat, result?.lng ] 옵셔널체이닝으로 사용되고 있습니다.
=>
calcCenterPoint의 빈 return 문을 {lat: null, lng: null} 로 변경하여 반환 타입을 맞추고 옵셔널 체이닝을 사용안합니다.
```

[Fix/halfway] calcCenterPoint.ts 반환 타입 맞추기, 타입 수정 및 적용

---

src/components/my-owl/profile/editable/UserInfo.tsx
src/components/my-owl/profile/editable/modal/Modal.tsx

closed #77 
closed #56 
```
유저가 프로필 사진을 올리면 프로필 상 화면에 보여줍니다. 
취소 버튼을 누르면 기존 프로필 이미지로 복원됩니다.
* 현재 상태 관리가 지역으로 되어있어서 코드 보기에 정신 없습니다! 
merge이후 상태 관리 로직 변경해서 새로 PR올릴 예정입니다.
```
```
프로필 수정 사항 반영을 어떻게 할 지 많은 고민을 했는데,
state를 사용하여 관리함으로써 생각보다 쉽게 해당 문제를 해결하였습니다.
추가적으로 유저가 사진을 업로드 하는 경우, 완료를 눌렀을 때 supabase storage에 업로드 되도록 하면 자원 낭비를 줄일 수 있어 더욱 좋을 것 같습니다. 
로직을 구현하다 보니, 마이페이지와 관련된 것들을 zustand로 전역 상태관리 해야할 것 같아 한 번 머지한 이후 상태 관리 전환하겠습니다!
```

[Feature/profile] 유저 프로필 사진 수정 사항 즉각 반영 및 수정 취소 클릭 시 기존 프로필 정보 복원

---

src/api/supabaseCSR/supabase.ts
src/components/my-owl/meeting/Meeting.tsx
src/components/room/meeting/calender/calculateOfMonth.ts
src/components/room/meeting/calender/checkSelectedDates.ts
src/types/supabase.ts

#85 
```
1. 기존에 존재하는 supabase의 쿼리 로직을 테이블 조인을 통해 하나로 합쳤습니다.
2. DB에서 필요한 정보들을 압축하고 클라이언트에서 실행하는 로직을 줄였습니다.
3. 실제 와이어프레임에 존재하는 확정일자(confirmed_data)를 사용하였습니다.
```
```
1. 로직을 합치는 과정에서 테이블 조인의 문제가 발생했습니다.
- 쿼리를 두 번 하는 것으로 해당 문제를 해결 할 수 있었습니다.
2. DB 클라이언트에서 실행하는 로직들을 간소화 시킬 때 타입문제가 발생하였습니다.
-  nullish value가 존재하기떄문에 옵셔널체이닝을 사용한 부분이 존재합니다.
3. 실제 와이어 프레임에 존재하는 데이터를 사용하지 않았기 때문에 추가하였습니다.
- 데이터를 입력식으로 반영했을 뿐 월/일 방식으로 변환이 필요한 로직이 존재합니다.
```
해당 로직은 useEffect를 포함한 커스텀 훅으로 분리가 가능 할 것 같습니다.
또한, supabase 내부에서 존재하는 컬럼의 타입에서 nullish 밸류를 삭제하면 더 견고한 타입을 지정 할 수 있을것으로 예상됩니다.

[Feature/db] my-owl/Meeting.tsx내부의 로직을 변경

---

src/api/supabaseCSR/supabase.ts
src/components/my-owl/meeting/Meeting.tsx
src/hooks/useGetCalendar.ts

closed #53
```
1. 기존에 추가되던 캘린더의 데이터를 realtime으로 적용합니다
2. 데이터를 fetch해오는 로직과 적용로직을 별도의 커스텀 훅으로 분리합니다
```
```
1. payload로 적용하는 부분의 로직을 단순 추가로 하여 수정이 아닌 추가만 되는 현상
- 캘린더 값의 변경된 id를 추적하여 적용시켰습니다.
3. 데이터를 realtime으로 적용하는 과정에서 초기 접속시 실시간 반영이 되지 않았던 문제가 있습니다.
- 의존성 배열에 start_date를 가지고 있는 userSchedules를 포함하여 실시간 반영이 되도록 적용하였습니다.
```

[Feat] 캘린더의 데이터를 realtime으로 적용

---

src/app/my-owl/page.tsx
src/components/auth/MeetingButton.tsx
src/components/layout/Header.tsx

#102 
```
기존 my-owl 내부의 Meeting
```
```
1. react-icon을 사용하는 방법에 미숙해서 image 파일을 직접 삽입하려고함
-  팀원들의 도움으로 해결
```

[feat] 기존 mypage의 Meeting 컴포넌트를 사이드 바 하위 경로로 위치를 변경.

---

src/components/auth/UserProfileButton.tsx
src/components/layout/Header.tsx
src/components/my-owl/profile/editable/modal/Modal.module.css

#99 
```
아직 컴포넌트는 분리하지 않은 상태입니다.
(사실 분리했는데, 제대로 적용되지 않아 현재 브랜치로 커밋 내역 일부를 옮겨서 PR 올렸습니다..ㅎ)
컴포넌트 분리 시 전역으로 관리하거나, props drilling 중 하나를 택해야 합니다.
내일 아침 시도해보고, 잘 되지 않으면 도움 요청하겠습니다.. ㅎㅎ
- 커스텀 디자인은 금요일 저녁/토요일에 일괄 진행 예정입니다
```
```
컴포넌트 분리 및 의존성 분리가 어렵네요. 
스크린샷에 첨부할 영상 찍다가 에러 발견했는데, 내일 수정해서 PR 올리도록 하겠습니다.
```

[feat/header profile] 유저 프로필 설정 UI/UX 를 모달로 수정

---

src/components/auth/MeetingButton.tsx
src/components/my-owl/meeting/Meeting.tsx
src/hooks/useGetSidebarData.ts

#119
#85 
```
1. Meeting 컴포넌트 내부에 존재하는 useEffect 로직을 커스 텀훅으로 분리했습니다.
2. Meeting 컴포넌트 내부에는 ui로직만 존재하도록 변경하였으며, 변수의 이름을 SidebarData로 작성하여 직관적인 판단이 가능해졌습니다
```
```
1. 변수 작명에 있어서 직관적인 내용 파악이 가능하게 만들게 되었습니다.
```

[feat] 기존 Meeting 컴포넌트 내부의 useEffect를 useGetSidebarData.ts 커스텀 훅으로 분리

---

src/components/auth/MeetingButton.tsx
src/components/my-owl/meeting/Meeting.module.css
src/components/my-owl/meeting/Meeting.tsx
src/hooks/useGetSidebarData.ts

closed #102 
```
사이드바를 전역에서 사용 할 수 있게 변경하였습니다.
사이드바 대신 글로벌 모달이라는 이름으로 변경하였습니다.
```
```
1. 사이드바 대신 모달창을 이용한 디자인을 채택
1-1. 모달창에는 사이드에서 출력되는 기능이 nextui에 존재하지 않았음
1-2. 모달창으로 변경하며 전반적인 컴포넌트의 이름을 변경
```

[feat] NextUI를 통해 버튼, 모달창 구현

---

src/components/auth/UserProfileButton.tsx
src/components/auth/UserProfileRead.tsx
src/components/auth/UserProfileUpdate.tsx
src/components/my-owl/profile/modal/Modal.tsx

closed #134
```
데이터 관리 흐름을 수정하고, 유저 프로필 설정과 관련된 코드들을 리팩터링 및 컴포넌트 분리를 진행하였습니다.
또한, 파일 업로드와 관련해 발생한 에러(유저가 파일을 선택하지 않은 경우)를 핸들링하는 로직을 추가해 버그를 잡았습니다.
```
추후 @gidalim 님과 UserProfile 등 헤더 관련 컴포넌트들을 적당한 파일을 만들어 옮기면 좋을 것 같아요.
```
useQuery를 통해 유저 데이터를 가져오는 과정에서 수정 완료 후에 유저 프로필 조회 화면으로 넘어가면 
가장 최신의 데이터가 아닌 이전의 데이터를 보여주는 문제가 있었습니다. 
또한, 수정 중 모달 밖을 나가는 경우에도 이전의 수정 사항이 저장되는 문제가 있었습니다.
이러한 문제를 해결하기 위해 데이터 관리 흐름을 위 사진과 같이 기획, 변경하였습니다. 
useQuery 대신 useEffect를 통해 렌더링 될 때마다 가장 최근에 데이터를 fetching하도록 하는 등, 
각 모달 화면에 맞는 데이터 fetching 로직을 작성하였습니다. supabase로부터 가장 최신의 data를 가져옵니다.
데이터 관리 흐름을 바꾸며 코드 리팩터링도 함께 진행하였는데, 이전보다 훨씬 깔끔한 코드가 되어 기분이 좋네요:-)
또한, 유저가 파일 선택을 취소 한 경우 에러가 발생하는 문제가 있었습니다. 이는 Undefined인 경우를 처리해줌으로서 해결하였습니다.
```

[Feature/header userprofile] 유저 프로필 설정 관련 컴포넌트 분리 및 리팩터링, 기타 에러 수정

---

src/components/room/meeting/calender/Calender.tsx
src/store/calendarStore.ts

```
```
```
type 선언 오류가 떴는데, 상태 하나로 두 개의 로직을 한꺼번에 처리하려고 하니 발생하는 문제였습니다.
변경된 값을 각각 setSelectedDate에 담을 수 있게 변경하였습니다.
```

[refactor/calendar] selectedDate를 zustand를 이용하여 전역상태로 관리

---

src/api/auth.ts
src/api/supabaseCSR/supabase.ts
src/app/layout.tsx
src/app/room/[id]/page.tsx
src/components/room/StartMeeting.tsx
src/components/room/sidebar/user/UserList.tsx
src/hooks/useGetCalendar.ts
src/utils/getCurrentFormattedDate.ts

- closed #141
- #67
- #107
```typescript
await queryClient.prefetchQuery<User | null>({
queryKey: ['auth'],
queryFn: getSession,
gcTime: Infinity
});
```
gcTime 무한으로 주는 옵션있다. 
- gcTime이 지나면 유저정보를 가져오지 못해 프로필에서 에러가 뜨는 것 -> 유저정보 가져오는 prefetchQuery gcTime무한으로 만듦 
- supabase 채널 실시간 구독 쿼리키가 같아서 구독이 안되던 문제 -> 각각 다른 채널이름으로 설정
- [실시간 채널 이름 중복 문제](https://www.reddit.com/r/Supabase/comments/16n33n9/realtime_subscriptions_to_multiple_tables/)
- [gcTime 알고싶은사람](https://velog.io/@tykim1227/react-query-%ED%8C%8C%EB%B3%B4%EA%B8%B0-%EC%BA%90%EC%8B%B1-%EB%9D%BC%EC%9D%B4%ED%94%84%EC%82%AC%EC%9D%B4%ED%81%B4)
- 마이페이지

[feat/fix] 시작 일자 이전 날짜 선택 차단,실시간 구독 문제, 유저데이터 가끔 못가져오는 문제 수정

---

src/api/room.ts
src/api/supabaseCSR/supabase.ts
src/app/room/[id]/(setting)/confirm/page.tsx
src/app/room/[id]/(setting)/pick-calendar/page.tsx
src/components/room/meeting/calender/Calender.tsx
src/components/room/meeting/calender/ResetSchedule.tsx
src/hooks/useGetCalendar.ts
src/hooks/useMutateUserData.ts

```
일정 설정 페이지 기존 선택한 날짜 초기화 버튼 생성
room_schedule 테이블 realtime event -> insert, delete 분리
날짜 선택 가능 범위 버그 수정
```
```
```

[fix/setting-schedule] 일정 설정 페이지 기존 선택한 날짜 초기화 버튼 생성, room_schedule 테이블 realtime event -> insert, delete 분리, 날짜 선택 가능 범위 버그 수정

---

src/app/login/page.module.css
src/app/room/[id]/layout.module.css
src/app/start/page.module.css
src/components/header/UserProfileButton.tsx

closed #174 
메인페이지를 제외한 다른페이지에서 화면을 줄였을 때 양옆 padding 추가 
```
const [profile, setProfile] = useState<string | null>('');
```
`UserProfileButton.tsx` 파일 에 있던 코드에서 기본값 null값 -> "" 빈 문자열로 수정
- 개발서버에서 null 요청오류뜨는지 확인
- 화면사이즈를 줄였을 때 양옆 여백

[fix] /null 로 GET요청 보내고 오류 내보내는 버그 수정

---

src/components/room/meeting/place/search/CategorySelector.tsx
src/store/placeStore.ts
src/types/place.types.ts

closed #188 
```
range-controller 에서 range가 번경될때 마다 전역으로 관리하는 searchOption 상태의 radius를 최신 range로 update 해준다.
searchOption 상태가 변경되면 keyword search  Query가 실행 !
새로운 반경의 검색 결과 반영!
```
```
```

[fix/range marker] 반경 변경시 카테고리 검색 결과 Marker가 유지되는 버그 수정

---

src/api/supabaseCSR/supabase.ts
src/app/room/[id]/(setting)/pick-calendar/page.tsx
src/components/room/meeting/calender/Calender.tsx
src/hooks/useGetCalendar.ts
src/hooks/useGetSchedule.ts

closed #190
```
기존 데이터를 받아오는 방식은 모든 유저의 스케줄을 한 번에 받아오는 구조였습니다.
이 구조를 커스텀 훅으로 분리하여, 모든 데이터, 나의 데이터, 나 이외 인원의 데이터로 필터하는 방식을 훅으로 제작하였습니다.
```
```
1. 리액트 쿼리를 사용하면서, 쿼리키에 대한 이해도가 부족한 부분이 존재했음
- 팀원의 설명을 통해 쿼리 키안에 캐싱데이터를 위한 매개변수를 받아오는 것을 이해하게 되었음
```

[feat] 유저캘린더에서 데이터를 받아오는 형식을 data, mydata, anotherUserData 로 분류

---

src/components/room/meeting/place/ResultMap.tsx
src/components/room/meeting/place/search/CategoryMarker.module.css
src/components/room/meeting/place/search/CategoryMarker.tsx
src/hooks/useMapController.ts
src/utils/place/calcHalfwayPoint.ts

closed #196 
```
CategoryMarker에 prop drilling 해주고 있는 id와 클릭 한 id 의 차이의 변화로 info card를 보여주고 안보여준다.
start_location 정보를 가지고 있는 유저가 있을 때 halfwaypoint의 위치값을 {lat: null, lng: null}로 반환해 NaN이 안 뜨게 한다.
```
```
```

[feat/pin-overlay] 카테고리 marker info card 보여주기 토글 기능, halfwayPoint 에서 start_location이 없을 때 NaN이 안뜨게 조건 로직 수정

---

src/app/room/[id]/(setting)/pick-calendar/page.tsx
src/hooks/useGetSchedule.ts

```
확정 페이지에서 일정 수정을 위해 pick-calendar 페이지로 넘어오면
내 일정은 파란색,  다른 유저의 일정은 보라색으로 구분하여 보여줍니다.
파란색 원을 다시 클릭 시, 수정된 내 일정이 세션 스토리지에 담깁니다.
```
```
pick-calendar 페이지를 들어가자마자 내 일정을 selectedDate, 즉 세션스토리지에 담아서
수정이 가능하게 하는 로직을 생각해내지 못해 calendar 페이지 안에서 한참 헤맸습니다...ㅎ
```
supabase의 데이터를 그 안에서 다시 필터링 한 후에 가져와서 사용하는 방법을 알았습니다.

[fix/calendar]: 일정 수정 시, 세션 스토리지에 저장 후 확정 페이지로 넘어감

---

src/components/header/ProfileModal.module.css
src/components/header/ProfileModal.tsx
src/components/header/UserProfileButton.module.css
src/components/header/UserProfileButton.tsx
src/components/header/UserProfileRead.tsx
src/components/header/UserProfileUpdate.tsx

closed #203 
`UserProfileRead.tsx`, `UserProfileUpdate.tsx` 컴포넌트 내부에 각각 `isOpen`을 구독하는 `useEffect`문을 만들고, 해당 훅의 콜백함수로 이벤트 리스너 등록 및 전처리(모달 닫기)를 해주었습니다.
0. 브라우저에서 라우팅 하는 방식을 공부한 후,  parallel route, route intercept등의 개념을 채택하여 모달의 기능을 구현하고자 했습니다. 
- 모달이 열려있을 때 앞으로가기/뒤로가기 버튼을 누르면 모달 안에서만의 라우팅이 되도록 한다.
- 프로필 조회 화면에서의 뒤로가기는 단순히 모달을 끄는 동작만 한다.
의 목적을 달성 하기에는 위 개념이 가장 적합하다 판단했기 때문입니다. 그러나 시도 중 몇가지의 한계가 존재하여 해당 방법으로의 구현을 포기하게 되었습니다.
```
1. 적용하고자 하는 모달은 페이지가 아닌 컴포넌트이다. 따라서 parallel router를 적용하려면 헤더를 페이지 형태로 전부 옮겨야 하는 대대적인 작업이 필요하다. 비용이 크다.
2. 적용하고자 하는 모달은 헤더 레이아웃으로 잡혀 있기에, route intercept를 하기 위해 헤더를 어찌 저찌 페이지 형태로 옮긴다고 한들 intercept해야 하는 경로의 수가 굉장히 많았다. (id에 대해서는 똑같이 동적으로 해주면 되지만, 각 과정에 대한 페이지 경로가 다양했다.) 
따라서 비효율적인 과정이라 판단했다.
```
2. 히스토리 스택의 특성을 이용해 모달 창이 띄워졌을 때 하나의 히스토리를 쌓는 방식을 채택하고자 했습니다. 모달 내에서 이동할 …

[fix/profile modal] 프로필 모달 창 뒤로가기 이슈 해결

---

src/app/room/[id]/layout.tsx

#206 
- [ x ] 카톡 인앱브라우저에서 링크 열기 시도할 때, 외부 브라우저로 호출하는 코드 추가
```
카톡 인앱브라우저에서 링크 열기 시도할 때, 외부 브라우저로 호출하는 코드를 추가했습니다.
카카오톡과 라인 이외의 앱 (ex. 틱톡, 스냅챗) 에서 다른 브라우저를 여는 코드 등의 
불필요한 코드는 제외했습니다. 
```
```
```
바로 테스트할 길이 없어 맞는 방법으로 코드를 추가한 건지 모르겠습니다ㅜㅜ
재상튜터님께서 알려주신 우회 코드의 홈페이지입니다.
https://burndogfather.com/271?source=post_page-----e6d6a424853--------------------------------
카카오톡/라인 등 인앱브라우저를 사용하는 이유를 처음 알았습니다.
https://brunch.co.kr/@b30afb04c9f54dc/45
dev에서 인앱브라우저 환경에서 제대로 작동하는지 테스트하려 했으나,
방법이 없어 보여서 배포 후 테스트가 필요할 것 같습니다..ㅜ

[fix/in app browser] 카카오톡 인앱브라우저에서 구글 로그인 시도 시, 403 에러

---

src/utils/groupBy.ts
src/utils/mostSchedule.ts

closed #211 
Object.groupBy가 새로운 JavaScript 문법이라, Babel에서 컴파일 하는 데 문제가 발생한 것으로 보인다. 아직 최신 문법의 적용이 모든 버전의 브라우저에서는 되지 않는  것 같아 해당 함수를 직접 구현하여 대체하려 한다.
일단, 모바일 브라우저에서의 개발자 모드를 확인해야 한다는 문제가 있었다. 이는 Mac Safari & Xcode simulator의 조합으로 확인하였다.
에러 화면은 아래와 같았다.
1. 우선 함수의 시그니처와 인터페이스를 알아보았다.
시그니처
```
인자로 items와 keySelector 를 받는다. 
이 때, items는 iterable이며 keySelector는 callback함수이다.
```
기존 groupBy에 정의된 인터페이스
```typescript
interface ObjectConstructor {
/**
* Groups members of an iterable according to the return value of the passed callback.
* @param items An iterable.
* @param keySelector A callback which will be invoked for each item in items.
*/
groupBy<K extends PropertyKey, T>(
items: Iterable<T>,
keySelector: (item: T, index: number) => K,
): Partial<Record<K, T[]>>;
}
```
2. 직접 정의하는 함수 타입과 구현체 …

[fix/error] iOS 및 기타 브라우저 최신 문법 적용 이슈 해결

---

src/components/room/StartMeeting.tsx
src/components/room/meeting/place/search/SearchBar.tsx
src/components/room/meeting/place/search/SearchResultList.tsx
src/hooks/useGeoLocation.ts

```
검색바 input을 useRef로 연결
검색바를 focus 하면 list를 보여주는 listViewState를 ture로 해준다.
결과 list를 클릭, 터치 하면 해당 위치로 이동과 함께 useRef로 input blur 해주고 listViewState를 false로 변경해준다.
start, setting 경로에 따라 기존의 위치를 보여줄지 gps 연동을 통해 본인의 위치를 보여줄지의 조건 로직 수정
모임 생성 시 이전 방에서 설정한 state를 초기화 해주기 위해 sessionStorage clear 해준다.
```
```
```

[fix/searchbar-focus] 검색 결과 list 표시 조건 수정, start와 setting 경로에 따라 첫 지도에 gps 연동 조건 수정

---

src/components/room/meeting/calender/Calender.tsx

```
이전에는 달력 렌더링의 기준이 오늘 날짜였습니다.
따라서 방장이 모임의 일정 범위를 지정하더라도 disabled 된
오늘 날짜의 해당 달이 화면에 보여졌습니다.
지금은 방장이 지정한 일정 범위의 시작 날짜를 기준으로 달력을 보여줍니다.
```
```
```

[fix/calendar]: 일정 페이지 입장 시, 범위를 기준으로 달력 렌더링

---

src/api/supabaseCSR/supabase.ts
src/components/header/profile/UserProfileUpdate.tsx
src/components/my-owl/profile/modal/Modal.tsx
src/utils/extractFileNameFromURL.ts

closed #227 
유저 프로필 업로드 시 용량 관리를 위한 최적화를 진행하였습니다.
삭제 경로 지정을 위해, 프로필 사진의 경로를 받아 이름을 추출하는 extractFileNameFromURL 함수를 작성하여 사용했습니다.
- 한 유저 당 스토어에 저장된 프로필 사진 파일은 무조건 하나가 되도록 로직을 수정하였습니다.
supabase store에서 파일을 삭제할 때, 이미지의 URL이 아닌 경로를 지정해서만 삭제가 가능합니다.
- https://supabase.com/docs/reference/javascript/storage-from-remove

[fix/optimize] 유저 프로필 업로드 시 용량 관리를 위한 최적화 진행

---

src/components/header/profile/UserProfileButton.module.css
src/components/header/profile/UserProfileRead.module.css
src/components/header/profile/UserProfileRead.tsx
src/components/header/profile/UserProfileUpdate.tsx

closed #231 
UI를 고려하여 닉네임 최대 길이를 8자로 수정하였습니다.
또한 프로필 조회 시 모바일 화면에서의 UI를 개선하고, 프로필 수정으로의 이동 버튼에 색상을 추가하여 UX를 개선하였습니다. 
추가적으로, 헤더의 프로필 사진 hover 시 outline-color를 키 컬러로 설정하여 통일감을 주었습니다.
<br/>

[fix/profile] 프로필 수정 시, 닉네임 입력 가능 글자 수를 최대 닉네임 글자수로 제한하기

---

src/api/supabaseCSR/supabase.ts
src/components/header/profile/ProfileModal.tsx
src/components/header/profile/UserProfileRead.tsx
src/components/header/profile/UserProfileUpdate.tsx
src/components/my-owl/profile/modal/Modal.module.css
src/components/my-owl/profile/modal/Modal.tsx
src/components/room/place/ResultMap.module.css
src/store/userProfileStore.ts

이미지 업로드 관련 비동기 데이터 처리 로직 강화 (새로고침 제외), 새로 고침 전 알림창 표시 작업을 하였습니다.
업로드 후 저장 전에 새로고침 하는 경우, 업로드 한 이미지를 삭제할 수 없습니다. (디비에서 삭제해야 함)
해결해보려고 온갖시도를 했지만, 브라우저 자체의 한계인 것 같습니다. (보안 이슈)
한국어로 검색해도 자료가 잘 안나와요. 보안 상 문제로 새로고침 시 비동기 작업, 커스텀 알럿창 작업이 불가능하도록 해놓은 것 같습니다.
누군가가 업로드하고 저장 하기 전 새로고침을 무한 반복하면,, 물론 최대 2MB로 업로드 제한을 해놓긴 했지만요..
보안 상 좋지 않은 이미지 처리 방식인 것 같아서 슬픕니다.
사실 첫 단추부터 잘못 끼워진 것 같은 느낌이 들지만...
(그래서 그런지 이미지 업로드 관련 로직이 매우매우매우 복잡한 상태입니다.)
시간 관계상 다 뒤집어 엎는 것은 힘드니 일단 이대로 가겠습니다 엉엉...
**나중에 디자인까지 끝나고 시간이 생긴다면 리팩터링 1순위입니다.**
그래도 새로 고침 전 알림창은 뜨게 해놨습니다.
- [프론트엔드 개발자라면 알아야 할 브라우저의 동작 과정](https://yozm.wishket.com/magazine/detail/1338/)
- https://leteu.tistory.com/17
새로고침 제외 모든 경우의 수를 테스트 해주세요.  
문제 생기면 저에게 알려주십시오 ㅎㅎ.....

[fix/image upload] 이미지 업로드 시 파일이 이중으로 업로드 되는 문제 해결 (새로고침 제외)

---

src/hooks/useGeoLocation.ts
src/hooks/useSettingMap.ts

```
지도 이동시 중심 위치 상태 반영에 걸려있던 debounce delay를 1초에서 200ms로 수정
-> 위치 이동 후 바로 위치지정 icon을 눌렀을때 delay 때문에 이동하기 전 위치로 고정 되던 현상 수정
설정 페이지 첫 접속시 start_location이 null인 경우도 있어 조건에 추가
```
```
```

[fix/setting-pin] debounce delay 200ms로 변경, gps 연동 조건 추가

---

src/components/room/place/StartLocationBox.tsx

```
출발 위치를 고정 했을 때 지도를 이동하면 고정된 출발 위치 내용이 현재 지도의 중심으로 나오는 현상 수정
-> isPinned 가 true일 때 db의 start_location을 보여주고 false일 때 store의 중심 위치 상태로 보여주도록 변경하였습니다.
```
```
```

[fix/start-location-box] 출발 위치 고정일 때 지도 이동 시 출발 위치 내용도 고정으로 수정

---

src/api/supabaseCSR/supabase.ts
src/components/room/calender/Calender.module.css
src/components/room/calender/Calender.tsx
src/components/room/calender/EntireOfMonth.module.css
src/components/room/calender/EntireOfMonth.tsx
src/components/room/calender/Schedules/Schedules.tsx
src/components/room/calender/Schedules/SchedulesOfMe/SchedulesOfMe.module.css
src/components/room/calender/Schedules/SchedulesOfUsers/SchedulesOfUsers.module.css
src/components/room/calender/Schedules/SchedulesOfUsers/SchedulesOfUsers.tsx
src/components/room/sidebar/MyRooms.tsx
src/components/room/sidebar/Sidebar.tsx
src/hooks/useSubscribeCalendar.ts
src/utils/calendar/checkIsSelectedDate.ts

(방에 참여한 유저 인원수별로 투명도 조절했습니다)
전반적인 달력의 css를 변경하였고, 유저가 선택한 날짜 표시와 다른 유저들이 선택한 일정에 대한 표시 방식에 조금의 변형을 주었습니다.
또, 사이드바 상단 로고 클릭 시 홈페이지로 이동하도록 하였으며, 각 방의 이름을 첫 글자로만 표시하였습니다.
방에 참여한 유저 인원수별로 투명도 조절하는 로직에서, 방에 참여하는 유저 인원을 실시간으로 설정해주고 싶은데 (실시간으로 css도 바뀌도록) 어떻게 해야할까요?
+유저 인원에 따라 다른 컴포넌트들도 같이 리랜더링 되어야하므로 props drilling을 사용하였습니다.

[style/calendar] 캘린더 관련 디자인 수정, 사이드바 일부 수정

---

src/api/supabaseCSR/supabase.ts
src/app/about/page.tsx
src/app/room/[id]/page.tsx
src/components/room/chatRoom/ChatMessage.tsx
src/components/room/chatRoom/ChatRoom.tsx
src/components/room/chatRoom/InitMessages.tsx
src/components/room/chatRoom/InputBox.tsx
src/components/room/chatRoom/ListMessage.tsx
src/components/room/chatRoom/Message.module.css
src/components/room/chatRoom/Message.tsx
src/store/messageStore.ts
src/types/supabase.ts

#260 
```
각 방마다 채팅정보를 받아오기 위해서 로직을 room 페이지로 이동시켰습니다.
현재 room내부에 한 자리를 차지하고 있기 때문에, 다른 로직을 적용할 시에 chatRoom 컴포넌트를 주석처리 해주세요.
realtime으로 받아오는 로직은 수행되고 있으나, 본인의 자료까지 보이기 때문에 추가 수정이 필요합니다.
모달창을 여닫을 때 데이터를 불러오는 로직을 보완해야합니다 ( 현재 출력이 안되고 있음 )
```
```
1. room으로 이동 후 room_id를 함께 저장하려고 했을 때상태를 수정하는 올바르게 DB에 등록되지 않는 부분이 부분에서 문제가 발생했습니다.
- 해당하는 페이지에 insert 값에 text와 room_id를 추가해주었습니다.
```
1. 채팅이 룸에 귀속된 것인지 체크해야합니다. (다른 방에서 채팅을 칠 때 그 채팅이 보이는 지 확인용도)
2. 다른 유저가 채팅을 칠 때 확인이 되는 지 체크해야합니다. ( 잘 적용이 되는지 체크 )

[Feat] room페이지로 로직을 이동시키고 채팅에 리얼타임을 적용시켰습니다.

---

src/app/room/[id]/page.tsx
src/components/room/chatRoom/ChatRoom.module.css
src/components/room/chatRoom/ChatRoom.tsx
src/components/room/chatRoom/InputBox.module.css
src/components/room/chatRoom/InputBox.tsx
src/components/room/chatRoom/ListMessage.module.css
src/components/room/chatRoom/Message.tsx
src/components/room/header/RoomHeader.tsx

closed #260
```
채팅 룸 내부의 모달창의 위치와, 모달 닫힘 방식을 개선했습니다.
모달 창은 우 하단에 존재하며 키 컬러인 보라색으로 삼았습니다.
또한 모달창 버튼을 상호작용하여 채팅을 여닫을 수 있고, esc 키와, x버튼을 통해 닫을 수 있습니다.
```
```
Next UI에서 제공하는 모달창은 지정된 커스텀만이 가능한데 
useDisclosure 내부에 존재하는 onOpenChange의 변수로는 버튼 토글을 구현 할 수 없었습니다. 
- 대신 onOpen과 onClose 를 통한 if문 분기처리를 통해 구현할 수 있었습니다.
```
실시간 채팅이 되는 것과, 최초 실행시 딜레이가 길다면 스피너 혹은 스켈레톤UI 사용을 고려해봄직합니다.

[Feat] 모달창의 버튼 디자인, 위치와 닫힘형식을 개선하였습니다.

---

src/components/room/calender/ResetSchedule/ResetSchedule.tsx
src/components/room/header/RoomHeader.module.css
src/components/room/header/RoomHeader.tsx
src/components/room/place/StartLocationBox.module.css
src/components/room/sidebar/MyRooms.tsx
src/components/room/sidebar/Sidebar.module.css
src/components/room/sidebar/Sidebar.tsx

1. 중심 위치 주소와 안내 문구를 타이틀에 표시하고 구분선을 추가했습니다.
2. 캘린더 하단에 참석 가능한 일정을 선택하도록 안내 문구 추가했습니다.
3. 모임 인원을 한 눈에 확인할 수 있도록 추가했습니다.
4. 툴팁 안내 문구를 추가했습니다.
```
```
의찬님께서 만드신 중심 장소 클릭 버튼을 merge 후 추가할 예정입니다.

[style/show center] 중심 위치 주소를 타이틀에 표시, 안내 문구 추가

---

src/api/supabaseCSR/supabase.ts
src/components/room/chatRoom/InputBox.tsx
src/components/room/chatRoom/ListMessage.tsx
src/components/room/chatRoom/Message.tsx
src/store/messageStore.ts
src/types/supabase.ts

closed #272 
```
채팅창을 토글 버튼으로 열었을 때 최상단에 멈춰있어서 매번 스크롤을 아래로 내리는 불편함이 존재했습니다.
이제 채팅창을 열거나, 새로운 채팅을 작성 할 때마다 하단으로 끌어내려집니다.
또한 채팅창을 불러오는 로직을 수정하여, 불필요한 데이터 요청을 줄이고, 정렬 로직을 사용하지 않아도 되도록 수정하였습니다.
```
```
타입오류가 존재했습니다.  messageEndRef.current.scrollIntoView 로직을 구현할 때 null일 수 있는 조건이 있었기 때문입니다.
- if문으로 채팅이 존재할 때만 해당 로직이 동작하도록 수정했습니다.
새로운 컬럼에 데이터를 추가하는 방법은 정상작동 하였으나, 출력이 undefined로 출력되는 문제가 있었습니다.
- 단순히 출력부에서 변경된 로직을 적용하지 않았기 때문에 생긴 문제입니다.
```
빠르게 채팅을 진행할 때 스크롤을 위로 올리면 끌어당겨질 것 같아서 이에 대한 테스트와 대응이 필요할 것 같아요

[feat] 새로운 채팅을 항상 하단에서 확인 할 수 있게 수정

---

src/app/auth/delete/route.ts
src/components/auth/DeleteAccountButton.tsx
src/components/header/Header.tsx
src/components/header/profile/UserProfileButton.tsx
src/components/header/profile/UserProfileRead.tsx

```
supabase.auth.admin.deleteUser로 DB에 유저 정보 삭제
https://oauth2.googleapis.com/revoke 에 google 외부 서비스 연결 해제 요청
https://kapi.kakao.com/v1/user/unlink 에 kakao 외부 서비스 연결 해제 요청
브라우저 콘솔에 dropdown menu와 item에 경고 표시 해결
-> 경고에 나와있는 방법대로 menu에 aria-label, item에 textView prop을 추가
```
```
- 회원 탈퇴를 하면 DB에 정보는 삭제 되지만 각 유저의 소셜 플랫폼과 연결이 끊기지 않아 다시 소셜 로그인을 시도 했을때 정보 제공 확인 절차 없이 바로 로그인 되는 문제가 생김
->  db에 삭제와 연결을 끊어주는 작업을 해줘야합니다.
- 각 플랫폼마다 연결을 끊기 위한 data가 다르다 kakao는 kakao user_id, google은 token이 필요하다
owl-link는 supabase의 auth서비스를 사용하기 때문에 해당하는 data가 어디에 있는지 찾는 어려움이 생김
->  kakao의 user_id는 supabase.auth.getUser()로 받아오는 user_metadata.sub 와 user.identities의 kakao provider 내용이 있는 객체의 id를 참조하면 됩니다.
->  google의 token은 supabase.auth.getSession()로 받아오는 session 정보에 provider_token을 참조하면 됩니다.
- 유저가 kakao, google 두 …
```

[feat/delete-account] 회원탈퇴 기능, 프로필 드랍다운 경고표시 해결 (aria-label, textValue)

---

src/components/room/chatRoom/InputBox.module.css
src/components/room/chatRoom/InputBox.tsx
src/components/room/chatRoom/Message.tsx
src/store/messageStore.ts
src/types/supabase.ts

#280 
```
inputbox 내부에 비행기 아이콘을 삽입하여, 채팅이 입력되고 있다면 아이콘의 색상을 변화시킵니다.
동시에 input태그 자체를 상태로 관리, value 유무를 추적하게끔 로컬 상태로 관리하였습니다.
```
```
비행기 아이콘을 변경시킬 때, value값의 상태관리를 통해서 관리하지 않았을 경우 텍스트가 업로드 된 이후에도 비행기의 색상이 보라색인 점을 발견하였습니다.
- 상태로 관리를 진행하여 해당부분을 정리했습니다. 아마도 비제어 컴포넌트와 제어컴포넌트 사이의 차이라고 생각이 됩니다.
```

[Feat] 채팅룸 내부의 inputbox 에 비행기 아이콘을 삽입

---

src/components/room/place/UserMarker.module.css
src/components/room/place/UserMarker.tsx

```
유저 프로필 이미지와 마커 핀 이미지를 겹처서 유저 마커를 커스텀 했습니다.
```
```
kakaoMap sdk에서 제공 해주는 Mapmarker의 스타일을 커스텀 할 수 없어서
CustomOverlayMap안의 children에 마커이미지와 프로필 이미지를 겹처서 해결했습니다.
마커 이미지와 프로필 이미지를 감싸는 div에 가운데 정렬을 하기 위해 
최상위 container를 relative 속성을 부여하고
자식 요소들 (marker, avatar)를 absolute 속성을 부여
top: 50%, left 50%을 주고 transfrom: translate(-50%, -50%)을 부여해 가운데 정렬을 했습니다.
```

[style/user-marker] 유저 마커 스타일 커스텀

---

src/components/room/chatRoom/InputBox.tsx
src/components/room/chatRoom/ListMessage.tsx

closed #280
```
채팅의 최소딜레이를 0.5초로 두었습니다.
```
```
알림창을 띄워주고 싶은데 0.5초는 너무 짧네요
```
채팅이 여러번 입력되는 버그가 해결 안됐다면 말씀해주세요.

[feat] 채팅의 최소딜레이를 0.5초로 고정

---

src/app/room/[id]/page.module.css
src/components/room/calender/EntireOfMonth.module.css
src/middlewares/protectRoute.ts

= Task TODOLIST
- 로그인하고 `/login` 페이지로 이동
- 모바일에서 사이드바 열고 닫기

[feat] 반응형 사이드바, 로그인 유저 로그인페이지 접근 막기

---

src/components/my-owl/meeting/Meeting.tsx
src/components/room/sidebar/MyRooms.tsx
src/components/room/sidebar/Sidebar.module.css
src/components/room/sidebar/Sidebar.tsx

1. 약간 왼쪽으로 치우쳐져 있던 방 나가기 버튼 위치를 조정했습니다.
2. 랜딩페이지와 현황페이지에서 다른 방을 클릭했을 때, 확정된 방이면 확정 페이지로 이동할 수 있게 수정했습니다.
```
```

[style/exit] 방 나가기 버튼 위치 조정 및 확정된 방 클릭 시 확정 페이지로 이동
